### ISSUE TITLE
Storing Data

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#1]
# Story
As a **developer** I want a **sensible way to store link data** so that **I can implement a link management solution for my user**.

# Acceptance criteria
- We have evaluated that the JSON and DataObject approach.
- We've confirmed which one is the best.
- We have evaluated the possibility of implementing the link filed in a generic way that allow other developers to use their own data store.
- Which ever solution is picked, it most support the addition of custom link types.
- Decision is recorded in subsequent cards for implementation.

# Note 
We've had issues in the past with the elemental data model. We explored using JSON fields instead of DataObject, but it's a bit clunky. We just need to validate that the DataObject approach won't have any unexpected downside.

**Comment by maxime-rainville** [comment]
@chillu From our own experience and from talking to the terraformers, we're leaning towards dropping the "link data as JSON" idea and implement each link type as a subclass of a generic `Link` DataObject.

We'll probably want to have a catch up with you soonish to identify some of the potential pitfall with this approach.

**Comment by chillu** [comment]
Is it better to close this and continue the discussion in https://github.com/silverstripe/silverstripe-linkfield/issues/30?

**Comment by dnsl48** [comment]
Yes, this one is rather the "actionable" card. We'll close it as a part of our sprint work soon.

**Comment by dnsl48** [comment]
`RFC-30` is finalised and ready for sharing with the community and keeping all data-model related discussions in there.
This issue can be closed when https://github.com/silverstripe/silverstripe-framework/pull/9817 gets merged
