### ISSUE TITLE
Link versioned history

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#10]
## Story
As a **CMS User** I want **to view old link instance when looking at previous version of my page** so that **I can restore old content with confidence**.

## Acceptance criteria
- LinkField display in ReadOnly view when looking at an older version of the page instead of the "Can not create Link" view.
- Version of link displayed follows whatever logic versioned history follows for other relations.
- Archived Admin uses the same behaviour as Versionned Admin when displaying link.
- LinkField on versioned history view correctly identify if a Link was attached to the page, but the Link was deleted.
- LinkField on versioned history view correctly identify if a Link was not attached to the version of the page currently being viewed.

## Note
- We do not have an overarching view of how relations should be displayed in compare view. We will ignore this part for now.
- We considered adding a history tab to the LinkForm, but decided it was out of scope for this card.

## Designs
[Link field - Overview](https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/build/folder/components/5fbc28d0096742ec25194c31?mode=preview)

## Note
The current implementation reuses the same IDs when you change Link Type. This could be a plus ... or a horrible hindrance ... not sure which one yet.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/209

**Comment by sachajudd** [comment]
@silverstripeux to look into what this would look like in history.

**Comment by maxime-rainville** [comment]
Cassie didn't think there was much value beyond making sure the LinkField is usable in the Versioned history view.

**Comment by maxime-rainville** [comment]
## What the diff looks like

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/4039e872-4ee9-4207-803b-ea10eecf8734)

## What the older version looks like
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/f8b147c0-15f7-435e-9a10-8d407d26bb45)

**Comment by GuySartorelli** [comment]
PR merged
