### ISSUE TITLE
Remove dead weight code

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#106]
As a CMS Squad, we don't want to carry forward code that is not needed to minimise our maintenance burden.

## Acceptance criteria
- [x] [`JSONField`](https://github.com/silverstripe/silverstripe-linkfield/blob/4/src/Form/JsonField.php) is folded back into [`LinkField`](https://github.com/silverstripe/silverstripe-linkfield/blob/4/src/Form/LinkField.php).
- [x] [`DBJson`](https://github.com/silverstripe/silverstripe-linkfield/blob/4/src/ORM/DBJson.php) and [`DBLink`](https://github.com/silverstripe/silverstripe-linkfield/blob/4/src/ORM/DBLink.php) are removed.
- [x] [`JsonData`](https://github.com/silverstripe/silverstripe-linkfield/blob/4/src/JsonData.php) is removed and all reference to it are substituted.
- [x] Module is still broadly functional.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/118

**Comment by emteknetnz** [comment]
Linked PR has been merged
