### ISSUE TITLE
Read only

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#11]
## Story
As a **CMS User** I want a **to know when a LinkField is in a readonly state** so that **I have a clear understanding that I can not edit this link**.

## Acceptance criteria
- [x] A read only UI for the link field has been designed and implemented in consultation with design team.
- [x] User can still look at the link data in the modal, but cannot interact with it when the field is in a Read only state.
- [x] Consider what to do with the existing `$this->getOwner()->canEdit()` checks on `LinkField.php` and `MultiLinkField.php` - see https://github.com/silverstripe/silverstripe-linkfield/pull/141#discussion_r1433406199

## Exclude
- Handling list of links with mix-permission.

## Note
- The Modal already has canEdit checks, so part is partially working.
- There's already checks at the API level to make sure you can't write object you don't have access to.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/172
- https://github.com/silverstripe/silverstripe-admin/pull/1652

**Comment by maxime-rainville** [comment]
@silverstripeux ^

**Comment by sachajudd** [comment]
Please see updated [designs](https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/build/folder/components/5fbc28d0096742ec25194c31?mode=preview).

**Comment by sabina-talipova** [comment]
Design team asked about the following changes:
- 'Update' button be grey instead of green so that is looks disabled.
- Fields to not be clickable at all. There should also be some sort of note in the pop-up saying that they don't have permission to edit the link.

**Comment by sabina-talipova** [comment]
Design team asked about info message for read only form. Something like this.

![Screenshot 2024-01-19 at 11 54 13 AM](https://github.com/silverstripe/silverstripe-linkfield/assets/87288324/ce09d18d-7fb4-466b-9914-87c7b843bb51)

**Comment by emteknetnz** [comment]
@sabina-talipova I've had a look at the AC `Consider what to do with the existing $this->getOwner()->canEdit() checks on LinkField.php and MultiLinkField.php - see https://github.com/silverstripe/silverstripe-linkfield/pull/141#discussion_r1433406199` and it seems like we don't need to change anything

I've ticked of the checkbox for that AC

**Comment by sabina-talipova** [comment]
> @sabina-talipova I've had a look at the AC `Consider what to do with the existing $this->getOwner()->canEdit() checks on LinkField.php and MultiLinkField.php - see https://github.com/silverstripe/silverstripe-linkfield/pull/141#discussion_r1433406199` and it seems like we don't need to change anything

@emteknetnz, do you mean we don't need to change UI if user use method `setReadonly`?

**Comment by emteknetnz** [comment]
No that's not what I meant

On the issue linked on that AC it referring to the value passed from PHP to JS in LinkField/MultiLinkField `$data['canCreate'] = $this->getOwner()->canEdit();` and if we need to update that based on the work we're doing in this PR.  I don't think we need to update it since this appear to be working as you'd expect them to
