### ISSUE TITLE
All AJAX calls should handle all possible errors gracefully

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#110]
## Story

As a content author, I want UI feedback when an HTTP request fail so I can take appropriate action with certainty.

## Notes
- Fairly sure that there are red toasts for failure already, we just need to double check this is the case

## Acceptance criteria
- All Linkfield AJAX requests are reviewed so they can handled error scenarios.
- Other unforeseen errors fail gracefully:
  - Server response timeout
  - Unexpected 500
  - Any other errors not already covered.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/161

**Comment by GuySartorelli** [comment]
PR merged
