### ISSUE TITLE
LinkField can be translated

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#113]
## Story

As a content author, I want the ability to use LinkField in my native language.

## Acceptance criteria
- [x] Module is added to Transifex.
- [x] All content string in JS and PHP are localisable.
- [x] All field labels for all Link models are translatable.

## Exclude 
- Initial string to translate are uploaded to Transifex. We want to wait until the keys are final.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/119

**Comment by emteknetnz** [comment]
Linked PR has been merged
