### ISSUE TITLE
Elemental support

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#116]
Assumes that the [PR to use FormSchema](https://github.com/silverstripe/silverstripe-linkfield/pull/108) for submissions has been merged

Linkfields do not work in elemental inline edit blocks.  Part of this reason may be the underlying HTML for the inline edit form is different than for a Page edit form, e.g.

**Page edit form:**
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/2d0cc2fd-89e4-4f03-9ed4-7a6b59b61eba)

**Elemental inline edit:**
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/61edd8b4-cfb5-4a8e-b5dd-4077159f2226)

Note that it don't think this works either with the existing stable version of linkfield either, I wasn't able to inline edit them either, though perhaps I was doing something wrong. I used the following code for my block:

```php
<?php

use DNADesign\Elemental\Models\BaseElement;
use SilverStripe\LinkField\Form\LinkField;
use SilverStripe\LinkField\Models\Link;

class AnotherBlock extends BaseElement
{
    private static $db = [
        'MyField' => 'Varchar',
    ];

    private static $has_one = [
        'MyLink' => Link::class,
    ];

    private static $table_name = 'AnotherBlock';

    private static $singular_name = 'Another Block';

    private static $plural_name = 'Another Blocks';

    private static $description = 'This is another block';

    private static $icon = 'font-icon-block-content';

    public function getType()
    {
        return 'Another Block';
    }

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->insertAfter('MyField', new LinkField('MyLink'));
        return $fields;
    }
}

```

**Comment by maxime-rainville** [comment]
It's working now.
