### ISSUE TITLE
Indicate when a new link has been added, but not yet saved to the relation

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-linkfield#121]
Currently if you add a new link, the save/publish buttons don't change to reflect that the link hasn't been saved - and the status of the link is "draft", which makes it sound like it has been saved into the page but just not yet published.
If the user doesn't save the page (or whatever object owns the link), the link is never saved into the relation, so it gets lost.

There's no current way to see that a link hasn't been saved to the relation yet. This is vital to avoid scenarios where users lose data.

## Acceptance criteria
- When a link is new, and has _not_ been saved to the relation on its owner, the status flag says "new" or "unsaved" or something similar, to clue the user into the fact that the link is not saved to the relation.
- OR, the link is automatically saved to the relation when it is created

## Notes
- This is _not_ the same as https://github.com/silverstripe/silverstripe-linkfield/issues/97 or https://github.com/silverstripe/silverstripe-linkfield/issues/7, which are about displaying and managing the versioned state of links - even when a link is in draft, there is no distinction between a link that _has_ been saved to the relation but is in draft, and a link that _has not_ been saved to the relation yet.

**Comment by emteknetnz** [comment]
Closing as fixed by https://github.com/silverstripe/silverstripe-linkfield/issues/145
