### ISSUE TITLE
Allow link types to have custom icons

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-linkfield#123]
If link types had their own icons, it would add some quick visual distinction between links of different types, which will help content authors quickly understand what they're looking at.

## Notes

Max had a PR where this was being implemented: https://github.com/silverstripe/silverstripe-linkfield/pull/45 - should be able to pick some stuff from this
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/ff0aecee-e2e0-47b4-9633-c319b55569c3)

## ACs
- There are different icons for different links types
- Documentation shows how to add custom icons to custom link subclasses

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/170

**Comment by GuySartorelli** [comment]
@sabina-talipova please link to the PR(s) in the issue description

**Comment by sabina-talipova** [comment]
> @sabina-talipova please link to the PR(s) in the issue description

Updated

**Comment by GuySartorelli** [comment]
PR merged
