### ISSUE TITLE
Provide feedback if a page/file link is missing its relation

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-linkfield#124]
Page and file links need a relation to a page or a file so they know what to link to.

There is (or will be) validation to ensure one is provided when the link is first created, but if that related object is later _deleted_, the link will still exist but will be missing the record it needs to provide a correct link.

There should be some feedback to content authors when such links exist - either in a report, with some visual indicator in the `LinkField`, or both.

Update: There is now visual feedback in the linkfield itself - so we need to decide if we want this information in a report (e.g. broken links report).

**Comment by maxime-rainville** [comment]
Following discussion with Cassie:
- This probably has some related concerns with the #8 card.
- We should probably aligned the two
  - If we do a broken link reports, links pointing to broken relation should be flag
  - The LinkField should flag any situation where a link should be considered broken (e.g. External link pointing to something that doesn't exist anymore)

Cassie thought we should prioritise this card.

**Comment by GuySartorelli** [comment]
> The LinkField should flag any situation where a link should be considered broken (e.g. External link pointing to something that doesn't exist anymore)

I don't think the linkfield itself should be firing off ajax requests to validate external URLs.

**Comment by GuySartorelli** [comment]
The display for missing relations is done - the broken link report is a separate issue so this is a duplicate now.
Max is creating another related but separate card about visual feedback for broken links more generally.
