### ISSUE TITLE
UX team is briefed on LinkField

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#125]
We need some UX feedback on how the LinkField is put together. 

## Acceptance criteria
- Design team is brief on current functionality of the module.
- Key missing UI are outline to the design team.
- Design team has access to a sandbox with the most up-to-date version of the module.
- Related UI (Anyfield and Upload filed) are provided to design team for comparison purposes.
- Coordination mechanism with the design team is agreed.
- Design team feel confident they can proceed.

## Initial mockup
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/a4397016-359e-4d03-88d7-4d74b87f9eeb)

**Comment by michalkleiner** [comment]
Could this be an RFC where community could contribute ideas if they have some specific use cases that could/should be considered? Don't want to drag the process but there might be some gems out there we wouldn't otherwise consider. Just a suggestion.

**Comment by maxime-rainville** [comment]
This card is more about setting up a coordination process with Silverstripe internal design team. I'm a bit weary of turning this into "Design by committee" exercise. 

If there's use cases that the LinkField is not currently covering and there's no cards for it currently, then people are obviously welcomed to jump in there raise cards for those. In fact, this is the perfect time for this since we're actively looking at formalising how the LinkFiled works.

**Comment by maxime-rainville** [comment]
Conversation has occurred and notes have been added to relevant card.
