### ISSUE TITLE
Add sort functionality to `MultiLinkField`

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-linkfield#139]
The `MultiLinkField` can't be sorted right now - we should add that functionality.

## Acceptance Criteria
- Content authors can click-and-drag links in the `MultiLinkField` to determine their sort order
- The default sort order for `Link` is the sort field (meaning links are automatically in the correct order in the front-end)
- Sort order is saved on click/drag.
- JS sorting library is chosen with care towards using a well maintained library and minimise our maintenance burden.
- UX team is consultated on the design.

## Notes
- The AnyField implementation provided this functionality, so we might be able to pull some of this from there.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/166

**Comment by maxime-rainville** [comment]
That's what the AnyField UI looks like right now. The handle comes from elemental.
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/c25476ee-a30e-41ac-b83e-ef0614f1f3ed)

**Comment by GuySartorelli** [comment]
PR merged
