### ISSUE TITLE
Use proper namespace for PHP translation

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#140]
We made the module localisable in https://github.com/silverstripe/silverstripe-linkfield/issues/113

However we don't appear to be using our regular convention for PHP translation key.

e.g.:

This line

https://github.com/silverstripe/silverstripe-linkfield/blob/7f65d4fdee873fc7746acdc82e3bc2b591138a02/src/Models/Link.php#L106

should be written

```php
_t(__CLASS__ . '.LINK_TYPE_TITLE', 'Link Type'),
// OR
_t(Link::class . '.LINK_TYPE_TITLE', 'Link Type'),
```

## Acceptance criteria
- All PHP translation keys use the standard approach used in other module.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/164

**Comment by GuySartorelli** [comment]
@emteknetnz Can you please link to any relevant PRs in the description?

**Comment by GuySartorelli** [comment]
PR merged
