### ISSUE TITLE
Hide the LinkFieldController form left and main

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#143]
## Accetpance criteria
- The LinkFieldController is hidden from left and main.

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/a60a98cc-d6f6-4992-99a6-9db47806c144)

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/144

**Comment by GuySartorelli** [comment]
PR merged
