### ISSUE TITLE
Handle cases where there is no owner

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#148]
As part of [saving the relation between an Owner and Link on Link creation](https://github.com/silverstripe/silverstripe-linkfield/issues/145) you can get into a state where the Owner has yet to be saved, such as creating a new Owner on a GridField.

In these instances, it probably makes sense to not render the LinkField component normally, and instead have a message in the LinkField along the lines of "Save the Owner first"

We can simply check to see if the ownerID prop in the LinkField component is `0` or not as a condition for showing the message

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/159

**Comment by GuySartorelli** [comment]
@emteknetnz Did you mean to open this in the linkfield repo?
I'll migrate it there

**Comment by GuySartorelli** [comment]
PR merged
