### ISSUE TITLE
Versioned UI state (of link owner record) after link creation and deletion

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#152]
After a link is created and the underlying parent object is directly saved in the database, [as part of this card](https://github.com/silverstripe/silverstripe-linkfield/issues/145), the versioned UI state should be correct

Examples:
- For a freshly published Page with a LinkField on it, when a new Link is added, the Page versioned UI state should be a clean Save button, and a dirty Published button.
- For a freshly published Content Block Page with a LinkField on a Content Block, when a new Link is added, the Content Block should have a modified versioned state, and the page its only should have a clean Save button, and a dirty Published button.

## Notes
- Should be able to use the existing javascript change tracker to update this, rather than directly updating the save and publish buttons via jquery

## Acceptance criteria
- [ ] The versioned state UI for pages is correct when new Links are added or deleted
- [ ] The versioned state UI for content blocks is correct when new Links are added or deleted
- [ ] If there are any _unsaved_ changes on the page/block at the time the link is added/deleted, the save button should remain in a dirty state.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/193

## New issues created
- https://github.com/silverstripe/silverstripe-admin/issues/1665

**Comment by sabina-talipova** [comment]
PR's merged. Task was completed.
