### ISSUE TITLE
Cannot select existing file in FileLink with smaller than lg breakpoint

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#156]
When selecting an existing file in FileLink, the LinkField shows 'File does not exist'.

This does not happen when uploading a new file.

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/e6c7ce8e-4d1b-4408-9fb3-4c9c0562682b)

**Update: Use a breakpoint less than 992px wide, which is the lg breakpoint in _bottostrap-variables.scss**

## Follow up issue created
- https://github.com/silverstripe/silverstripe-admin/issues/1662

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/190

**Comment by sabina-talipova** [comment]
@emteknetnz , could you, please, provide steps to reproduce this issue. Test locally and didn't see any problem.

 
<img width="465" alt="Screenshot 2024-01-11 at 12 54 34 PM" src="https://github.com/silverstripe/silverstripe-linkfield/assets/87288324/122f997c-a692-4a7a-9978-643b16bbc68b">

**Comment by emteknetnz** [comment]
1. Create a FileLink on either a has_one or has_many relationship
2. Upload a new file
3. Delete the FileLink
4. Refresh the page (otherwise you'll run into an asset-admin caching issue and you won't see the newly uploaded file)
5. Create a new FileLink
6. Select the recently uploaded file
7. LinkField says "File does not exist"

**Comment by sabina-talipova** [comment]
Still see path as a File Link.
<img width="469" alt="Screenshot 2024-01-11 at 1 38 15 PM" src="https://github.com/silverstripe/silverstripe-linkfield/assets/87288324/483e281d-e897-48dc-ad33-e1d4ff904f86">

**Comment by GuySartorelli** [comment]
I saw this happen once (in a fresh environment) - but when I tried to reproduce it (in that same environment), it didn't happen a second time. Seems like this one's gonna be a bit finicky.

**Comment by emteknetnz** [comment]
This likely has something to do with the file selection modal getting into a weird state. You can replicate this by doing something unusual and clicking the 'details' button on a selected file and clicking "Save" on the file, rather than the "Insert" button.  When you do you don't go back to the LinkFieldModal with this 'Create/Update Link' button, instead you go straight back to the page edit form - likely it's this existing issue - https://github.com/silverstripe/silverstripe-linkfield/issues/114

I cannot replicate via normal use though on a fresh install though.  I've keep this issue open for now though in case anyone manages to find a reliable way to replicate

**Comment by emteknetnz** [comment]
Way to replicate this is to use a breakpoint of less than 992px wide when selecting the file, that changes the green insert button from

```
<button type="button" value="insert" class="bulk-actions__action font-icon-plus-circled btn-primary btn btn btn-primary">Insert</button>
```
To
```
<button type="submit" id="Form_fileSelectForm_action_insert" name="action_insert" class="btn btn-primary font-icon-plus-circled action"><span class="btn__title">Insert file</span></button>
```

Have updated title and description

**Comment by GuySartorelli** [comment]
PR merged
