### ISSUE TITLE
Tidy up hover/active/focus state styling

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#168]
Hover/active/focus state styling is a bit of a mess

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/c006a72b-8653-45bc-b389-a0bfbc703d32)

## Acceptance criteria
- Check with design team what they'd like done (probably just make everything have a white background and unchanging border to match elemental)
- Implement design suggestions

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/191

**Comment by sabina-talipova** [comment]
PR's merged. Task is completed.
