### ISSUE TITLE
Validation of standard link types

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#17]
## Story
As a content author, I want LinkField to block me from inputting invalid data.

## Acceptance criteria
- Appropriate logic is applied - e.g. external links must have a URL, page links must have a Page, etc.
  - PageLink should have a page
  - EmailLink should have a valid email address
  - External link should have a valid full URL 
  - Phone link should have a non blank string but not otherwise validate the phone number
  - File link should point to a valid CMS file.
- We use form validation for validating the data.
- The LinkField doc is updated to link to the form validation article in the main doc.

## Exclude
- Displaying the validation error in a front end. https://github.com/silverstripe/silverstripe-linkfield/issues/16

## Guy's PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11123
- https://github.com/silverstripe/developer-docs/pull/454

## Steve's PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11116
- https://github.com/silverstripe/silverstripe-linkfield/pull/85
- https://github.com/silverstripe/developer-docs/pull/450

**Comment by maxime-rainville** [comment]
We have already partially implemented this in the process of re factoring bits of the linkfield.

Maybe this card just become a doc card.

**Comment by GuySartorelli** [comment]
PRs merged
