### ISSUE TITLE
Clicking Archive/Delete button should give "are you sure" prompt

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#175]
When inline archive an element, you get this prompt:

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/7d6549ea-01d0-4b43-9da2-54614845b545)

LinkField should do the same when clicking Archive/Delete, rather than the instant delete that happens now. People could easily misclick it.

## Acceptance criteria
- The user needs to confirm they want to delete the link before it gets deleted.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/188

**Comment by GuySartorelli** [comment]
PR merged
