### ISSUE TITLE
Link type title and icon are not displayed if link record exist, but link type is not longer available for creating

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-linkfield#176]
## Description
If a link type was initially available, but later this link type was excluded from the list, then the link is still available for viewing and editing, but this type is not available for creation and the name of the link type and its icon are not displayed.
Should we use a default Link title and icon if link exist, but link type is not longer available?

## PR
-  https://github.com/silverstripe/silverstripe-linkfield/pull/177
- https://github.com/silverstripe/silverstripe-linkfield/pull/180

## Related issue
- https://github.com/silverstripe/silverstripe-linkfield/issues/178

**Comment by GuySartorelli** [comment]
PR merged
