### ISSUE TITLE
Move and rename `Title` field

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-linkfield#179]
In the modals, could I suggest moving the field for the linked item to the top, so it's the first item a user sees, and then the optional extra fields like "Title" and "Open in new window?" below it?

**Before:**
![external-before](https://github.com/silverstripe/silverstripe-linkfield/assets/329880/37793b6a-a216-43f1-9164-1e77a1202fad)

**After:**
![external-after](https://github.com/silverstripe/silverstripe-linkfield/assets/329880/3fc94dbb-0287-48c3-bf46-eb2c2bcf6998)

For context, the WYSIWYG has the link text field below the URL or equivalent fields:
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/36352093/897eae3e-515d-4220-9874-78d8896717f4)

## Acceptance criteria
- "Title" label is rename "Link text". 
- DB field is renamed `LinkText`.
- Developers migrating from older version of the module can get their `Title` converted to `LinkText` and have clear guidance about how to do that.
- "Link text" is de-prioritise.
- "Link text" warning is switched to use the "Hint" API.
 

## Note
There's an API that got introduced in CMS4 to rename DB Fields to something else. It should still be there in CMS 5 and could be used to migrate Title to LinkText.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/207

**Comment by emteknetnz** [comment]
That makes sense to me. We'll bring this issue into our team refinement to discuss

**Comment by maxime-rainville** [comment]
We had a discussion about this and we're 100% sure this is a beneficial change. We'll have a chat with our UX team to discuss what makes most sense.

The Title field is a bit unconventional in this context. So maybe we want to have an overarching discussion about it

**Comment by maxime-rainville** [comment]
Following discussion with Cassie, we concluded:
- Renaming "Title" to "Link text" would be advisable. (I don't think we need to rename the underlying DB field)
- The order from the WYSIWYG is better to the current order.

**Comment by GuySartorelli** [comment]
PR merged
