### ISSUE TITLE
Disabled state

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#181]
Need to support a disabled state which is set via `->setDisabled(true)`

This is similar though not quite the same as `->setReadonly()` which had supported on [this card](https://github.com/silverstripe/silverstripe-linkfield/issues/11)

For example, with very quick test locally shows that there is a mouse pointer with the readonly field, though there isn't one with the disabled field

```php
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();
        $fields->insertAfter('Content', new TextField('MyText01'));
        $fields->insertAfter('Content', (new TextField('MyText02'))->setReadonly(true));
        $fields->insertAfter('Content', (new TextField('MyText03'))->setDisabled(true));
        return $fields;
    }   
```

Some differences between readonly and disabled can be found [here](https://stackoverflow.com/questions/7730695/whats-the-difference-between-disabled-disabled-and-readonly-readonly-for-ht)

## Acceptance criteria
- When `setDisabled` is set to `true`, the field renders with the read only styles and the user can not update the value.
- There's a [follow up card](https://github.com/silverstripe/silverstripe-linkfield/issues/182) to block any updates in the backend for readonly/disabled field.

## Notes
- We discussed whether disabled or readonly should have any practical difference. We concluded it wasn't really worth treating them as separate use cases.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/189

**Comment by sabina-talipova** [comment]
PR is merged. Task is completed.
