### ISSUE TITLE
Migration path from other modules

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#19]
# Story
As a **Developer using another link module** I want **a migration path** so that **move my existing content to this module**.

# Acceptance criteria
- We've identified the best migration path
- A follow up card has been created

# Note
There's two broad ways we could achieve this:
- we set up the link field so it can work with other data format ... this would allow other module to use our link field with their own data model
- we provide a migration script for the more common module

That's the most popular link field module: https://github.com/gorriecoe/silverstripe-linkfield

**Comment by GuySartorelli** [comment]
We already have other cards for these which are either already merged or in progress.
