### ISSUE TITLE
Publishing a FileLink and SiteTreeLink's does not publish linked File/SiteTree objects

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#192]
When the Page save button is click, any child Links are published.  However in the case of FileLink and SiteTree link which link to separate versioned records, though linked records are not themselves published

This probably is a good think in the case of SiteTreeLink, though in the case of FileLink, particularly when it was uploaded via the UploadField on the FileLink, this may be confusing, particularly because the FileLink's versioned badge indicates that it's published.

Likely what we want to do here is simply provide some messaging that you need to seperately publish the File/SiteTree in order for things to work as expected, rather than cascade publishing the linked object which is probably an undesirable side effect.

## Acceptance criteria
- Developer doc calls out the risk of publishing a link without publishing the file/page and explains how to define ownership if desired.
 
## Rejected ACs
- If a content author selects an unpublished file in a File link, they are warn that they have to publish the file.
- If a content author selects an unpublished page in a Page link, they are warn that they have to publish the page directly.
- The warnings is not displayed if the Link Model owns its relation.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/218

**Comment by maxime-rainville** [comment]
We collected some feedback from bespoke dev that auto publishing files and pages via Link was not advisable.

**Comment by maxime-rainville** [comment]
I wrote the draft ACs in the most expansive way imaginable, I'm not actually convinced this is worth doing in this way.

**Comment by GuySartorelli** [comment]
I'd just do the top one and leave the rest alone.

**Comment by maxime-rainville** [comment]
We rejected the idea of displaying an explicit message as it might be confusing for developers who decide to do alternative approaches to publishing files.

**Comment by GuySartorelli** [comment]
PR merged
