### ISSUE TITLE
Adjust the alignement of the icon in the LinkType selection drop down.

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#194]
There's some tweaks to the UI to address.
![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/5db3829f-fb60-421c-85f7-9a36706a3e8a)
The link icon are misaligned in the drop down view.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/220

**Comment by GuySartorelli** [comment]
The first two are duplicates of existing issues.
The third one isn't an issue at all - there will always be _some_ title (whether explicit or default).

I think the only relevant part here is the icon misalignment.

**Comment by GuySartorelli** [comment]
PR merged
