### ISSUE TITLE
SPIKE Is there a need for a "No text" link

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#199]
There may be some use case where a developer does not want a link text to be attached to the link. e.g. The link will be attached to an image.

## TODO
- Validate to what degree this is needed.
- Identify possible solution that a developer could do "as-is" without changing anything to the core link field.
- Identify possible change we could put in place to better support this use case.

**Comment by GuySartorelli** [comment]
I really think we're overthinking this - a simple setter takes no time to implement and solves what I can promise you is a real-world use case.

**Comment by emteknetnz** [comment]
Yeah agree SPIKE seems very pointless

**Comment by maxime-rainville** [comment]
From the feedback we collected at our session with our bespoke devs today, I'm happy to progress this feature.

**Comment by GuySartorelli** [comment]
The card for implementing this is https://github.com/silverstripe/silverstripe-linkfield/issues/211
