### ISSUE TITLE
Default title for each link type

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#20]
## Story
As a **CMS User** I want **the link to default  to a sensible title based on it's type and the provided data** so that **I can have a good experience when editing links**.

## Acceptance criteria
- [ ] The "Default title" approach has been validated with UX team.
- [ ] Whenever the Link title field is left blank, the default title is substituted when rendering the link on the front end.
- [ ] The Linkfield's title field will stay blank when not provided.
- [ ] Feedback is provided to the user that they can leave LinkField title field blank.
- [ ] An approach has been implemented allowing developers to implement default title for each link type.
- [ ] The default title mechanic has been determined for each built-in link type and applied.
- [ ] Documentation has been provided to developers so they can implement a default title logic for their own link type.

## Designs
[Link field - Overview](https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/build/folder/components/5fbc28d0096742ec25194c31?mode=preview)

## Note
- Something like that has already been partially implemented. It might just be a question to validate that all they ACs have been met and/or refactoring things bit.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/126

**Comment by brynwhyman** [comment]
More thinking required for this one from @silverstripeux. Some early thoughts discussed with @clarkepaul:

* * Leave the title field blank
* Leave the title field blank, make it a required field
* Default to the URL of the link
* Custom logic for each link type to provide sensible defaults (like Page title, Email contact, Phone number, etc)

Noting that where data objects have been left without a title it's caused issues in the past where it comes to reporting on things like the Used On table. So I'd say that first option should be a no-go.

**Comment by GuySartorelli** [comment]
Merged. See https://github.com/silverstripe/silverstripe-linkfield/issues/128 for a follow-up concern this has made me think of.
