### ISSUE TITLE
Loading indicator and error state

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#21]
# Story
As a **CMS User** I want **I want to know when the LinkField component is loading data** so that **I'm aware I can not interact with the field**.

# Acceptance criteria
- A proper loading indicator is displayed 
- When loading data from the backend fails an suitable error is communicated to the user

# Designs
[Link field - Overview](https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/build/folder/components/5fbc28d0096742ec25194c31?mode=preview)

# Note
We've got a mis aligned loading indicator right now
![image](https://user-images.githubusercontent.com/1168676/100075654-1adb6700-2ea5-11eb-8aef-1ea502dde89b.png)

We don't currently have an error state.

**Comment by GuySartorelli** [comment]
Already done
