### ISSUE TITLE
Add config option so more esoteric link types can be removed from list of default link

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#212]
By default, all link types are available in a LinkField. If a developer wants to disable a specific Link type, they have to do so for each instance of LinkField.

There could be some situation where this is not advisable. e.g. A link type is meant to be an "abstract" parent class for child classes or an esoteric link type only makes sense in a specific context.

## Acceptance criteria
- A configuration flag is added to Link classes specifying if they should show by default in LinkField.
- Root Link class can not be enabled via this API no matter what.
  - All other built-in Link subclasses are enabled by default.
- Disabling a Link classes prevent it from showing as an option in a vanilla link field.
- Disabled Link class can be added back to specific LinkField instance via the `setAllowedTypes` method.
- The feature is documented in the developer docs.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/219

**Comment by GuySartorelli** [comment]
> Link is disable by default. All other built-in Link subclasses are enabled by default.

I think `Link` should just be explicitly excluded at all times. This makes it both easier to implement this config flag in a sensible way, and means people won't go "Ooh I can turn `Link` on" and have a non-funcitonal link implementation that doesn't actually link to anything.

**Comment by sabina-talipova** [comment]
PR's merged. Task is completed.
