### ISSUE TITLE
Selectively removed the "Open in new tab" option based on link type.

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#23]
# Story
As a **CMS User** I want **the ability to get links to open in new tab where it makes sense**

# Acceptance criteria
- The "Open in new tab" option is the last form field by default.
- The "Open in new tab" option is removed from `PhoneLink` and `EmailLink`.

# Designs
[Link field - Overview](https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/build/folder/components/5fbc28d0096742ec25194c31?mode=preview)

# Note
All Link type currently have that option displayed, including some where it doesn't make sense like the Email Link type.

The placement of the option is also weird, because it the second option all the time, which give it an undue prominence.
 
![image](https://user-images.githubusercontent.com/1168676/100077347-1e6fed80-2ea7-11eb-8012-650108688f5a.png)

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/187

**Comment by maxime-rainville** [comment]
Paul says: 
- leave to user to decide by default.
- always display it at the end
-

Developers who are implementing custom link type will be responsible for removing the checkbox if they think it's not relevant.

**Comment by GuySartorelli** [comment]
PR merged
