### ISSUE TITLE
Migration from sheadawson/silverstripe-linkable

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#230]
As a developer maintaining a project using `sheadawson/silverstripe-linkable`, I have a a clear path and clear guidance on how to migrate to v4.

## Acceptance criteria
- An automated task exists to converts `sheadawson/silverstripe-linkable` data to v4 linkfield format.
  - The task accounts for versioning and all pre-existing links are assumed to be published.
  - Task can be extended to accommodate unusual usage of LinkField.
- Clear guidance on how to migrate to LinkField v4 is provided
- Guidance covers the scenario where a project is upgraded all the way from CMS 4.
- Guidance explicitly mentions that it is the developers responsibility to implement logic to cover custom link types.
- Guidance covers how to completely remove the `linkable` module.
- Guidance mentions feature gap between two linkfield implementations, but leave the developer to resolve these issue themselves.
- Migration task is marked as `@deprecated`.
- The task is disabled by default. 

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/261

**Comment by GuySartorelli** [comment]
FYI @sabina-talipova We discussed in standup today - these migration tasks have missed the cut-off for making it into the 4.0.0 stable release, so we'll need to target the `4` branch for them to be included in a future minor release.

**Comment by sabina-talipova** [comment]
For further implementation, it is required that this [PR](https://github.com/silverstripe/silverstripe-linkfield/pull/253) be merged into the main branch 4 first. New trait is required.

**Comment by GuySartorelli** [comment]
@sabina-talipova the gorriecoe migration PRs have all been merged now

**Comment by GuySartorelli** [comment]
PR merged
