### ISSUE TITLE
Question: MultiLinkField beta release

### ISSUE THREAD

**Issue by DanielTate** [silverstripe/silverstripe-linkfield#238]
### Description

Question.

I wanted to know if there is a release scheduled for the MultiLinkField ( even in beta ), it looks very helpful. If not is there another way you suggest getting multi links? using a different package perhaps?

Currently I'm on ^3.0@beta using this package has been nicer than the other options so far the only thing missing is MultiLinkField.

**Comment by GuySartorelli** [comment]
The release schedule for the 4.x line will be happening at the same time as CMS 5.2.0. We aim to release a beta in the next couple of weeks, with the stable release coming in April.
