### ISSUE TITLE
FileLink default text link should be the File Title

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#240]
### Module version(s) affected

4.x-dev

### Description

File Link should use the File title as their default title. It's currently using the Filename including the path.

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/9c97f855-de85-4063-a8e4-db88a8d50049)

### How to reproduce

1. Add a link to file.
2. Do not provide Link text.
3. Save your link text

Expected results: the Title of the link matches the title of the file.
Actual: The Filename of the File is the Title of the link

### Possible Solution

Fix this line:
https://github.com/silverstripe/silverstripe-linkfield/blob/b6dcef0a273e43267ed1f608c461414bf7c716af/src/Models/FileLink.php#L53

### Acceptance criteria
- The default title of FileLink is the File Title.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

### PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/248

**Comment by maxime-rainville** [comment]
This should be trivial to fix, but I'm putting it in Refinement first to give people a chance to disagree with me.

**Comment by GuySartorelli** [comment]
PR merged
