### ISSUE TITLE
LinkField needs fluent's gridfield removed so modal renders

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#243]
Fluent will add a tab with a gridfield to linkfield, however because there is no react component for gridfield, you'll get a hard error on the frontend and the link modal will not work at all

To work around this on the [SPIKE](https://github.com/silverstripe/silverstripe-linkfield/issues/210#issuecomment-1943029385) added a workaround `protected $schemaDataType = self::SCHEMA_DATA_TYPE_STRUCTURAL;`, though this shouldn't be merged as the lack of a gridfield component should hard fail so that developers are prompted to remove gridfields

## Acceptance criteria
- When fluent is installed, the tab with the gridfield is removed so that it does not render in the link modal

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/247

**Comment by GuySartorelli** [comment]
PR merged
