### ISSUE TITLE
Add deprecation warnings to v3

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-linkfield#246]
This was originally part of https://github.com/silverstripe/silverstripe-linkfield/issues/228

As a developer maintaining a project using LinkField v2/v3, I have a a clear path and clear guidance on how to migrate to v4.

## Acceptance Criteria
- [ ] Deprecations warnings are added to v3 for any [public API](https://docs.silverstripe.org/en/5/project_governance/public_api/) which was removed in v4
- [ ] The upgrade guide is updated to say to upgrade to (either `3.x-dev`, `3.0.0`, or `3.0.0-beta2` depending on the below) and resolve any deprecation warnings before migrating.

## To be decided by @maxime-rainville:
- Do we want to tag a `3.0.0-beta2` with the deprecations? Or just leave them on the `3` branch? Or tag stable?

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/269
- https://github.com/silverstripe/silverstripe-linkfield/pull/270

**Comment by maxime-rainville** [comment]
I think we need to tag something. My preference would be to tag 3.0.0 stable.

If that's not practical, 3.0.0-beta2 will work.

**Comment by GuySartorelli** [comment]
PRs merged, reassigned to Steve for whatever's left

**Comment by emteknetnz** [comment]
Assigning to @maxime-rainville to decide what to do regarding tagging

**Comment by maxime-rainville** [comment]
Unless someone is telling me that tagging 3.0.0 stable is not advisable, that is still my preferred option.

**Comment by emteknetnz** [comment]
3.0.0 stable was released https://github.com/silverstripe/silverstripe-linkfield/releases/tag/3.0.0
