### ISSUE TITLE
New Link get a Sort of 1

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#258]
I suspect that part of the problem is that new Link, seem to default to having a `Sort` of `1`.

## Repo steps
- Start with a list of 4 links.
- Sort them around so they all have an order set to them.
- Publish your changes
- Create a brand new link.
- New link is added at the end of the list
- Refresh the page

Expected results: New link is at the end of the list.
Actual results: New link is in the second spot.

If you look at the DB, you'll find that the new link has a Sort of 1. It's showing up in the second spot because one other link will have a Sort of 1.

[linkfield-2024-03-18_17.07.39.webm](https://github.com/silverstripe/silverstripe-linkfield/assets/1168676/4188fe0e-1ed6-48bb-9c80-d06fbcbfe495)

## Acceptance criteria
- Newly created links in a Link List are added to the end of the list and have the matching sort value assigned to them.

## Related card
https://github.com/silverstripe/silverstripe-linkfield/issues/254

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/262

**Comment by GuySartorelli** [comment]
PR merged
