### ISSUE TITLE
Dev docs

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#27]
# Story
As a **Developer** I want to **understand how the LinkField module work** so that **I can use it effectively in my own projects**.

## Acceptance criteria
- [ ] ~~All docs in the repo is moved to the official developer docs and removed from the repo.~~
- [x] A single link to tho official doc article is added to the LinkField Read Me
- [x] Changelog is updated to prominently call out this new feature.
- [x] Developer docs explains how to use links and link fields.
- [x] Developer docs explains how to create custom link types.
- [x] Developer docs explains how to render Links in templates and how to override the default template.
- [x] Developer link doc has been reviewed as a whole.
- [x] Add linkfield to supported modules list

## Note
There will be a separate card for user help.

## PRs
- https://github.com/silverstripe/silverstripe-linkfield/pull/224
- https://github.com/silverstripe/developer-docs/pull/457
- https://github.com/silverstripe/doc.silverstripe.org/pull/286

**Comment by DanielTate** [comment]
This should be higher priority. How do I use this field in my templates for example? There are no docs on this it seems.

**Comment by emteknetnz** [comment]
Since this is an optional module dev docs should remain be in README.md, not doc.silverstripe.org

**Comment by GuySartorelli** [comment]
Regarding "All docs in the repo is moved to the official developer docs and removed from the repo.", I had a discussion on slack with Max about this.
Instead we will be moving the docs into the `docs/en/` directory in the module, and having the developer docs site pull content from there (like userhelp pulls a bunch of its docs from other modules).

**Comment by emteknetnz** [comment]
Assigning back to Guy to confirm that everything deployed correctly

**Comment by GuySartorelli** [comment]
Docs site didn't break so that's a good sign lol.
We won't be able to check fully until we add a `4.0` branch fo linkfield and get the docs site to pull from `5.2` in developer docs.
