### ISSUE TITLE
Communicating between backend and frontend implementation

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#32]
Follow up from https://github.com/silverstripe/silverstripe-linkfield/issues/2

# Acceptance criteria
- [ ] The direction outlined in https://github.com/silverstripe/silverstripe-linkfield/issues/2#issuecomment-765105316 is implemented
  - [ ] The Entwine LinkField uses the "JSON in hidden input" approach to load the Data
  - [ ] The React LinkField uses the "form-schema" approach to load the Data
  - [ ] The basic implementation of the backend-frontend comms is abstracted with an eye to making it reusable
  - [ ] All interactions backend/frontend during the editing of links use the "expose AJAX endpoint through field" approach
  - [x] ~Data is validated before the link is updated~
  - [ ] Initial link description is loaded with initial data
  - [ ] Link description is refreshed once the link data is updated
  - [ ] Updated link data is communicated to the backend when the parent form is posted and saved along it's owner DataObject
- [ ] The end result works with
  - [ ] Legacy entwine form
  - [ ] JSON Post form-schema form like elemental
  - [ ] Regular Post form-schema form like the File editor

**Comment by brynwhyman** [comment]
Note that we've removed the AC: "Data is validated before the link is updated" as implementing validation will be covered in another issue. For this issue, just consider that there will be a validation error state.

**Comment by maxime-rainville** [comment]
No longer relevant.
