### ISSUE TITLE
CMS 5.3.0-beta1 regression: "Failed to load link" with anchor links

### ISSUE THREAD

**Issue by GuySartorelli** [silverstripe/silverstripe-linkfield#333]
When adding a link to a "page on the site" with `silverstripe/linkfield` inside an elemental block, we get this error when publishing (unclear if it's publishing the page or the block)

> Failed to load link(s)

![image](https://github.com/user-attachments/assets/121d5d26-6698-49ab-b95b-ffcd2156c1c7)

Note that the correct link displays after refreshing the page.

## Steps to reproduce

Note this assumes you have `silverstripe/frameworktest` installed, along with the rest of kitchen sink.

1. Add Link List Block
3. Go to Single Link 
5. Select Add Link
7. Select Page on the site from dropdown
9. Select a page
11. Add Anchor
13. Select Update link
15. Link should display in DRAFT mode
17. Select Publish

## PRs
- https://github.com/silverstripe/silverstripe-linkfield/pull/335

**Comment by GuySartorelli** [comment]
Can reproduce this - though some of the steps are a bit odd (why does it say "update link" in the instructions when you haven't even created it, for example?)

**Comment by GuySartorelli** [comment]
Frustratingly cannot reproduce this locally.
The environment I am able to reproduce it in is https://cmstestm-prod.sites.silverstripe.com/ which is PHP 8.3

**Comment by GuySartorelli** [comment]
I suspect it is a result of this:

![image](https://github.com/user-attachments/assets/483d1829-53fe-4e37-b1d4-794edf75f4eb)

The correct URL is https://cmstestm-prod.sites.silverstripe.com/admin/linkfield/data?itemIDs[]=95 (which it does eventually try) but for some reason the ID is split into two for the first request (https://cmstestm-prod.sites.silverstripe.com/admin/linkfield/data?itemIDs[]=9&itemIDs[]=5)

I'll try reproducing locally with IDs in the double digits.

**Comment by GuySartorelli** [comment]
Can reproduce locally now - getting the exact same split ID problem when running in my local with double-digit IDs.

**Comment by emteknetnz** [comment]
Linked PR merged
