### ISSUE TITLE
Improvement: SiteTreeLink to return Page Title as default if no $Title provided

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-linkfield#34]
It would be good if `SiteTreeLink` could return the linked Page's `Title` as a fallback when no explicit `Title` was set on the `Link` model.

**Comment by mfendeksilverstripe** [comment]
@chrispenny  Fixed in https://github.com/silverstripe/silverstripe-linkfield/pull/37

**Comment by mfendeksilverstripe** [comment]
Fix is now merged.
