### ISSUE TITLE
File in FileLink is not published when the Link itself is

### ISSUE THREAD

**Issue by UndefinedOffset** [silverstripe/silverstripe-linkfield#340]
### Module version(s) affected

4.0.7

### Description

The FileLink link type does not own it's file so when the link is published either through a recursive publish or directly the file itself is left in draft.

### How to reproduce

Have a Link as either a has_one or has_many relationship on an object that owns the link relationship. Then add a file link to a newly uploaded file which will be then in draft only. If the object with the link relationship is versioned publish the object if not save. Then look at the file link, the file itself will not have been published.

### Possible Solution

The easy fix to this is to add an owns configuration to the file relationship on FileLink.

### Validations

- [X] Check that there isn't already an issue that reports the same bug
- [X] Double check that your reproduction steps work in a fresh installation of [`silverstripe/installer`](https://github.com/silverstripe/silverstripe-installer) (with any code examples you've provided)

**Comment by GuySartorelli** [comment]
This is working as expected. Please see the documented [gotchas](https://docs.silverstripe.org/en/5/optional_features/linkfield/gotchas/)

**Comment by UndefinedOffset** [comment]
@GuySartorelli I can understand the reasoning for that stance, however the AX/UX is pretty poor if that is going to be the stance. It's not immediately obvious in the CMS ui if that is the case, the link will appear to be published but the file will not be and it's not clear that is the issue until either you look at the front end, or edit the link in the backend. Perhaps there needs to be some kind of indication on the link field itself that the file is not published.

**Comment by GuySartorelli** [comment]
If you can think of how that would look, I welcome you to raise a separate card proposing new UX for it.
For the time being, if you want the file to be published when the link is published, there's a solution in the documentation I linked to.
