### ISSUE TITLE
Missing elemental method on AbstractLinkField

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#346]
After merging https://github.com/silverstripe/silverstripe-elemental/issues/1268 there's now an issue as the old method no longer exists

```
1) SilverStripe\LinkField\Tests\Form\AbstractLinkFieldTest::testElementalNamespaceRemoved
Error: Call to undefined method DNADesign\Elemental\Controllers\ElementalAreaController::removeNamespacesFromFields()
```

## PRs
- https://github.com/silverstripe/silverstripe-linkfield/pull/347

**Comment by GuySartorelli** [comment]
PR merged
