### ISSUE TITLE
Possibility to specify an upload folder

### ISSUE THREAD

**Issue by bumbus** [silverstripe/silverstripe-linkfield#356]
### Description

It looks like, right now it is not possible to set the folder a FileLink will upload new files into.
Or at least I have not found a way.
I believe this feature will be a great addition to this module.

### Validations

- [ ] You intend to implement the feature yourself
- [X] You have read the [contributing guide](https://docs.silverstripe.org/en/contributing/code/)
- [X] You strongly believe this feature should be in core, rather than being its own community module
- [X] You have checked for existing issues or pull requests related to this feature (and didn't find any)

**Comment by GuySartorelli** [comment]
Thanks for submitting this.
Sounds like a good idea. I note you haven't ticked the "You intend to implement this feature yourself" checkbox. 

As per the [contribution guide](https://docs.silverstripe.org/en/contributing/issues_and_bugs/#feature-requests):
> Please don't file feature requests as GitHub issues. If there's a new feature you'd like to see in Silverstripe CMS, you either need to write it yourself (and [submit a pull request](https://docs.silverstripe.org/en/contributing/code/#step-by-step-from-forking-to-sending-the-pull-request)) or convince somebody else to write it for you. Any "wishlist" type issues without code attached can be expected to be closed as soon as they're reviewed.

While this seems like a useful feature, the CMS Squad doesn't have time to prioritise it in the immediate future. I'm going to close this issue for now, but if you want to submit a pull request implementing this feature yourself feel free to do so and let me know, and I'll re-open the issue.
