### ISSUE TITLE
Shipping this thing 

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#4]
# Story
As a **product owner** I want **to release this module early** so that **I can encourage early adoption**.

# Acceptance criteria
- We've identified how this functionality will be release and obstacles preventing early release.
- We've identified how we can involve the community in the process.
- We've communicated our commitment clearly to the community.
- We tag v0.x early and often.

**Comment by maxime-rainville** [comment]
Just confirmed with @blueo that having tags to target would be helpful for their work. I'm thinking let's just start tagging `0.x` version and start shipping quick iteration of the module.

**Comment by GuySartorelli** [comment]
This will be handled as part of the regular minor release process
