### ISSUE TITLE
Make link type labels and order consistent with WYSIWYG

### ISSUE THREAD

**Issue by purplespider** [silverstripe/silverstripe-linkfield#40]
When adding a link to a page this module uses the terminology "Site Tree Link" in the UI, but I don't believe the term "Site Tree" is used anywhere else in the CMS.

For clarity and consistency can we make the terminology the same as when inserting a link via the WYSIWYG, e.g.:
<img width="183" alt="Screenshot 2021-11-15 at 11 16 49@2x" src="https://user-images.githubusercontent.com/329880/141772950-2ddffbe0-c665-4291-9d06-48406a01a858.png">

Current linkfield module for comparison:
<img width="173" alt="Screenshot 2021-11-15 at 11 17 11@2x" src="https://user-images.githubusercontent.com/329880/141772994-464b5dc7-0a8b-446d-a1d0-defc944f455d.png">

(I started trying to do this myself, but unfortunately I don't do React).

## Acceptance criteria
- The labels in the LinkField drop down are updated to match the equivalent label in the WYSIWYG drop down
  - "SiteTree Link" is updated to be "Page on this site".
- The Link titles remain unchanged everywhere else.
- The options in the LinkField drop down are displayed in the same order that they're in with the WYSIWYG drop down

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/167

**Comment by purplespider** [comment]
@maxime-rainville How can I get some eyes on this? Do you agree? Any potential complications?

**Comment by maxime-rainville** [comment]
We're doing a bunch of work on this right now. I've added this to the backlog.

**Comment by GuySartorelli** [comment]
PR merged
