### ISSUE TITLE
CMS Anchor link

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#6]
# Story
As a **CMS user** I want **the option to link to an anchor in that context** so that **it's straight forward to create links**.

# Acceptance criteria
- We have validated whether treating SiteTree link and anchor link as one link type makes more sense than treating it as two distinct types.
- Link type models have been updated accordingly

# Note
The current set up use the regular anchor filed.
![image](https://user-images.githubusercontent.com/1168676/100080645-f3879880-2eaa-11eb-9bee-19628482947f.png)

 The [PUX design has a fancier UI for this](https://projects.invisionapp.com/share/YGGYS6HDMRK#/screens/343286662_Links).

**Comment by sachajudd** [comment]
@maxime-rainville this is a separate issue: https://github.com/silverstripe/silverstripe-cms/issues/2440
Please try not to add screenshots to issues, linking off is best as the designs are constantly updated. I can add headings to refer to if that makes it easier?

**Comment by maxime-rainville** [comment]
Removed the screen shot of the design.

**Comment by maxime-rainville** [comment]
That's already been done
