### ISSUE TITLE
Link as Required Field doesn't appear to work

### ISSUE THREAD

**Issue by chrispenny** [silverstripe/silverstripe-linkfield#69]
```php
class MyBlock extends BaseElement
{
    private static array $has_one = [
        'CtaLinkPrimary' => Link::class,
    ];

    private static bool $inline_editable = false;

    public function getCMSFields(): FieldList
    {
        $fields = parent::getCMSFields();

        $fields->addFieldsToTab(
            'Root.Main',
            [
                TextField::create('Title'),
                LinkField::create('CtaLinkPrimary'),
            ]
        );

        return $fields;
    }

    public function getCMSCompositeValidator(): CompositeValidator
    {
        $composite = parent::getCMSCompositeValidator();

        $composite->addValidator(RequiredFields::create([
            'Title',
            'CtaLinkPrimaryID',
            // Also tried:
            'CtaLinkPrimary',
        ]));

        return $composite;
    }
}
```

## Result

`Title` field correctly displays error, but `LinkField` does not.

![Screen Shot 2023-06-14 at 12 57 44 PM](https://github.com/silverstripe/silverstripe-linkfield/assets/505788/ecd5afa5-5aa1-4009-b842-d9bbc0e0a693)

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11119
- https://github.com/silverstripe/silverstripe-linkfield/pull/195
- https://github.com/silverstripe/silverstripe-framework/pull/11122

**Comment by GuySartorelli** [comment]
That's quite possibly a problem with `RequiredFields` rather than with linkfield. I imagine you'd get the same result if you were using https://github.com/silvershop/silverstripe-hasonefield and tried to set a `HasOneField`'s value as required.

**Comment by sabina-talipova** [comment]
Hi @chrispenny, 
I don't know, but probably it could helps to find some idea. I add new class that extends `LinkField's FormFactory` and implements `getValidator()`. Please, see test steps in [this PR](https://github.com/silverstripe/silverstripe-admin/pull/1578).

**Comment by maxime-rainville** [comment]
We'll validate if this is still a problem and fix it if it is.

**Comment by GuySartorelli** [comment]
PRs merged
