### ISSUE TITLE
Versioned by default

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#7]
## Story
As a **CMS user** I want **the ability to control the publication state of links through it's page (or other parent object)** so that I can view draft version and restore older version.

## Acceptance criteria
- The versioned extension is applied to the Link Object.
- The LinkField UI provide feedback about the publication state of the link
- The need to define ownership is made explicit in the documentation.
- Links can still be used if they are unversioned.
- UX team provides feedback and guidance on how to implement the versioned UI.

## Related
- https://github.com/silverstripe/silverstripe-linkfield/issues/97
- https://github.com/silverstripe/silverstripe-linkfield/issues/10

## Note
- Project will need to use ownership relations are used to publish/unpublish links. It will be the responsibility of individual project to configure that.
- This draft may be useful https://github.com/silverstripe/silverstripe-linkfield/pull/90/files

## Designs
[Link field - Overview](https://projects.invisionapp.com/dsm/silver-stripe/silverstripe-cms/nav/build/folder/components/5fbc28d0096742ec25194c31?mode=preview)

## New issues created
- https://github.com/silverstripe/silverstripe-elemental/issues/1124

## Pull requests
- [ ] https://github.com/silverstripe/silverstripe-linkfield/pull/90

**Comment by sabina-talipova** [comment]
PR is merged. Issue was fixed.
