### ISSUE TITLE
Technical Risk Analysis

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#80]
Before doing a substantial piece of work on linkfield, we should do a risk analysis to make sure we've capture risk and identifed proper controls to mitigate them 

## Acceptance criteria
- A Risk matrix is prepared
- The Risk Matrix identify risk and assigned a baseline probability and impact
- Controls are identified to mitigate the risk.
- Controls are spun up as separate cards.
- The Risk analysis reference the [OWASP top-10](https://owasp.org/www-project-top-ten/) where appropriate.

## Related
- [Example risk matrix](https://docs.google.com/spreadsheets/d/1iDnHU9Ojm3dC5PZWkY0s_OA1dmcwWiM0-4qi-XR6WBQ/edit#gid=657938453) (Silverstripe staff only)

**Comment by emteknetnz** [comment]
[Risk Matrix](https://docs.google.com/spreadsheets/d/1G7MTJTU_-e_GtjAEGsfJEm_r0mPZny0g4qil3tjrUQc/edit?usp=sharing) (Silverstripe staff only)


I'll create github cards once we've agreed on the risks and controls

**Comment by GuySartorelli** [comment]
I don't really understand this process well enough to do a proper review, but I have added a comment to the spreadsheet of one thing I noticed.

**Comment by maxime-rainville** [comment]
I've added a few extra risk. Admittedly, some of them are quite neat picky like "if you submit the page and the server crashes, you'll loose your link data".

I also rename some of them to be more OWASP-Top-10-ish.

Can you have a glance and fill in any missing controls?

**Comment by emteknetnz** [comment]
Updated 

I've deleted the "if you submit the page and the server crashes, you'll loose your link data" risk because while that's a technical risk - it's not a security risk and this matrix all about security, i.e. it talks about "(Confidentiality, Integrity, Availability)" on the "Risk Matrix" sheet

**Comment by maxime-rainville** [comment]
I'm happy with the analysis. I've created cards to implement any missing control.

I would quibble with the notion that "if you submit the page and the server crashes, you'll loose your link data" is out of scope for this. That's clearly a data integrity risk. But it's a very minor one and we can discuss this when we review our technical risk assessment methodology.
