### ISSUE TITLE
Used On table

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#9]
This should already work automatically, though we need to double check it works

## Acceptance criteria
- There is a relationship between FileLink and Link object in the asset-admin used of table when you click on file details

## PRs
- https://github.com/silverstripe/silverstripe-framework/pull/11107
- https://github.com/silverstripe/silverstripe-linkfield/pull/157

**Comment by sachajudd** [comment]
@silverstripeux

**Comment by GuySartorelli** [comment]
PRs merged
