### ISSUE TITLE
Can't view link behaviour

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#94]
## Story
As CMS Site owner, I want only authorised user to be able to see Link Data.

## Acceptance criteria
- LinkField can handle the scenario where a user has access to a page but not the Link.

## Note
Admittedly this is an edge case, I think we can just call it a day display a simple, "you don't have access to this link" message.

**Comment by GuySartorelli** [comment]
Done alrady
