### ISSUE TITLE
Linkfield UI can communicate its versioned state

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#97]
## Story
As a content author, I want to know what is the publication state of my Link.

## Acceptance criteria
- If the Link is not versioned, not versionning indicator is present
- If the Link is published, a suitable versionning indicator is shown.
- If the Link is in draft only, a suitable versioning indicator is shown.
- If the Link is published, but has unpublished change, a suitable versioning indicator is shown.
- The versioning indicator don't clash with the "dirty" state.

**Comment by GuySartorelli** [comment]
Done already
