### ISSUE TITLE
LinkField is covered by comprehensive Behat test coverage

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#98]
## Story
As a dev team, we want to know when our re-factoring is breaking things.

## Acceptance
- LinkField has comprehensive test coverage covering the current basic scenarios.
- Both Entwine and Elemental scenarios are covered.

## Note
- Maxime had to create a [side module](https://github.com/maxime-rainville/silverstripe-linkfield-tester) to test this properly in AnyField.
- We should be able to use DataExtensions with `TestOnly`.
- We may do a follow up card to cover more esoteric use cases later on.

## PR
- https://github.com/silverstripe/silverstripe-linkfield/pull/201
- https://github.com/silverstripe/silverstripe-frameworktest/pull/162

**Comment by sabina-talipova** [comment]
List of Behat Test scenarios:
- Link / MultiLink field is added to the page
- Link / MultiLink field has full list of link types
- Link / MultiLink field has restricted list of link types (test setAllowedTypes())
- Link / MultiLink field is disabled
- Link / MultiLink field is readonly
- Link type has proper link type title and icon
- Created links have proper link type title and icon
- Link / MultiLink has versioned badge
- User can create link of each type
- User doesn’t have permission to create link
- User can modify existing link of each type
- User can reorder links in MultiLink filed
- User can delete link
- In the Elemental Area:
  - Link / MultiLink field can be added to a Block
  - Link / MultiLink field in the Block is disabled / readonly
  - Link / MultiLink field in the Block has restricted list of link types
  - Link type has proper link type title and icon
  - Created links have proper link type title / icon / versioned badge
  - User can create link of each type
  - User doesn’t have permission to create link
  - User can modify existing link of each type
  - User can reorder links in MultiLink filed
  - User can delete link
- Save / Publish buttons state

Update:
- LinkField accessibility
- Render Links on a Page
- Render Custom Link title on a Page
- Render Default Link title
